Feat/feed page
puppypawpaw/pawpaw-client pull request #18
Opened 2023-08-03 14:21 UTC by jiyeeeah

## PR Type
해당 PR 은 어떤 변경 사항들이 있나요?

- [ ] 버그 수정
- [ ] 기능 추가
- [ ] 코드 스타일 업데이트 (포맷팅, 로컬 변수)
- [ ] 리팩토링
- [ ] 빌드 관련 변경
- [ ] 문서 내용 변경
- [ ] 기타... 설명:

## Key Change
- 피드 페이지
- 무한스크롤 구현
- 상단 게시글 업로드, 헤더 부분

## To Reviewers
혹시 제가 또 놓친 사항이나 의견 있다면 주저없이 코멘트 주세요! 더욱 예쁜(?) 코드를 위해..!

2023-08-04 03:19 UTC, taejinii commented on app/(main)/layout.tsx
> +      <Feed />
Feed 는 page.tsx에 들어가야하지않나요??

2023-08-04 04:47 UTC, JeonInguk requested changes

2023-08-04 04:47 UTC, JeonInguk commented on components/pages/Feed/index.tsx
> +      <FlexBox direction="column" className={`w-[1028px] gap-[40px] ml-[295px]`}>
혹시 백틱을 중괄호로 감싼 이유가 있으신가요??

2023-08-04 04:55 UTC, jiyeeeah commented on app/(main)/layout.tsx
> +      <Feed />
제가 layout이랑 page의 다른점을 몰랐어서 아무데나 둔 것 같아요 ㅠㅠ 찝어주셔서 넘 감사드려요!

2023-08-04 05:03 UTC, taejinii approved these changes

2023-08-04 07:06 UTC, taejinii commented on components/pages/Feed/index.tsx
> +      <FlexBox direction="column" className={`w-[1028px] gap-[40px] ml-[295px]`}>
이부분은 스켈레톤컴포넌트를 만들어서 로딩중일떄 스켈레톤컴포넌트를 보여주면 레이아웃시프트 현상을 없앨수 있을것같습니다.

2023-08-05 03:22 UTC, jiyeeeah commented on components/pages/Feed/index.tsx
> +      <FlexBox direction="column" className={`w-[1028px] gap-[40px] ml-[295px]`}>
3번에서 채팅리스트는 오른쪽 상단에 픽스된채로 떠있어야해서 제가 건드리기는 어려울 것 같아요..! 태진님께서 채팅 리스트에서 건드리는게 좋을 것 같습니다!

2023-08-05 03:35 UTC, jiyeeeah commented on components/pages/Feed/index.tsx
> +      <FlexBox direction="column" className={`w-[1028px] gap-[40px] ml-[295px]`}>
그리구 폰트색이나 border색상 등은 디자인시스템 만든 후에 수정해도 괜찮을 것 같습니다!

2023-08-07 06:22 UTC, JeonInguk approved these changes

2023-08-07 07:04 UTC, merged