Feat/comunity page
puppypawpaw/pawpaw-client pull request #23
Opened 2023-08-12 16:45 UTC by taejinii

## PR Type
해당 PR 은 어떤 변경 사항들이 있나요?

- [ ] 버그 수정
- [x] 기능 추가
- [ ] 코드 스타일 업데이트 (포맷팅, 로컬 변수)
- [ ] 리팩토링
- [ ] 빌드 관련 변경
- [ ] 문서 내용 변경
- [ ] 기타... 설명:

## Key Change
해당 PR은 어떤 변경 사항들이 있나요?

<img width="1432" alt="image" src="https://github.com/puppypawpaw/pawpaw-client/assets/96623949/15a96824-6239-44e9-ab35-2b6ef5473b5c">

Swiper 라이브러리를 사용하여 캐러셀을 구현하였습니다.

무한스크롤을통해 데이터를 불러오는 컴포넌트를 추가하였습니다.

## To Reviewers

디자인시스템에 버튼쪽이 미흡한 부분이 있어 버튼쪽을 추후 수정할예정입니다.

2023-08-12 18:41 UTC, JeonInguk requested changes
1. 피그마상에 보이는 'EnteredChatList, RecommendChatList, TrendingChatList' 간의 위아래 갭 차이가 필요해보입니다.
2. 사이드바의 사이즈전환 토글을 눌렀을때 'TrendingChatList' 반응형 작업이 필요할 것 같습니다.

2023-08-12 19:11 UTC, taejinii commented
> 
1. 피그마상에서 값이 확인이안되는데 어떻게 확인할수있을까요?
2. TrendingChatList는 grid 로 구현하여서 반응형 은 적용이 되어있는데 어떤 반응형 을 말씀 하시는걸까영?

2023-08-13 05:25 UTC, JeonInguk approved these changes
LGTM 수고하셨습니다~

2023-08-13 05:28 UTC, jiyeeeah approved these changes
수고하셨습니다!

2023-08-13 05:36 UTC, merged